timetable={
            'monday': {
                {'h1':
                     {'sub':'maths',
                     'Tchr':'lf',
                     'Rno':'129'
                     }
                },
                {'h2':
             {'sub':'ds',
             'Tchr':'sd',
             'Rno':'121'
             }
            },
                {'h3':
             {'sub':'py',
             'Tchr':'ar',
             'Rno':'122'
             }
            },
                {'h4':
             {'sub':'st',
             'Tchr':'nz',
             'Rno':'123'
             }
            },
                {'h5':
             {'sub':'se',
             'Tchr':'al',
             'Rno':'124'
             }
            }
               },
           'tuesday':{
                {'h1':
                 {'sub':'maths',
                 'Tchr':'lf',
                 'Rno':'129'
                 }
                },
                {'h2':
                 {'sub':'ds',
                 'Tchr':'sd',
                 'Rno':'121'
                 }
                },
                {'h3':
                 {'sub':'py',
                 'Tchr':'ar',
                 'Rno':'122'
                 }
                },
                {'h4':
             {'sub':'st',
             'Tchr':'nz',
             'Rno':'123'
             }
            },
                {'h5':
             {'sub':'se',
             'Tchr':'al',
             'Rno':'124'
             }
            }
           },
            'wednesday':{
                {'h1':
                 {'sub':'maths',
                 'Tchr':'lf',
                 'Rno':'129'
                 }
                },
                {'h2':
                 {'sub':'ds',
                 'Tchr':'sd',
                 'Rno':'121'
                 }
                },
                {'h3':
                 {'sub':'py',
                 'Tchr':'ar',
                 'Rno':'122'
                 }
                },
                {'h4':
             {'sub':'st',
             'Tchr':'nz',
             'Rno':'123'
             }
            },
                {'h5':
             {'sub':'se',
             'Tchr':'al',
             'Rno':'124'
             }
            }
            },
            'thursday':{
                {'h1':
                 {'sub':'maths',
                 'Tchr':'lf',
                 'Rno':'129'
                 }
                },
                {'h2':
                 {'sub':'ds',
                 'Tchr':'sd',
                 'Rno':'121'
                 }
                },
                {'h3':
                 {'sub':'py',
                 'Tchr':'ar',
                 'Rno':'122'
                 }
                },
                {'h4':
             {'sub':'st',
             'Tchr':'nz',
             'Rno':'123'
             }
            },
                {'h5':
             {'sub':'se',
             'Tchr':'al',
             'Rno':'124'
             }
            }
            },
            'friday':{
                {'h1':
                 {'sub':'maths',
                 'Tchr':'lf',
                 'Rno':'129'
                 }
                },
                {'h2':
                 {'sub':'ds',
                 'Tchr':'sd',
                 'Rno':'121'
                 }
                },
                {'h3':
                 {'sub':'py',
                 'Tchr':'ar',
                 'Rno':'122'
                 }
                },
                {'h4':
             {'sub':'st',
             'Tchr':'nz',
             'Rno':'123'
             }
            },
                {'h5':
             {'sub':'se',
             'Tchr':'al',
             'Rno':'124'
             }
            }
            }
           }

print(timetable['monday']['h1']['sub'])
print(timetable['tuesday']['h2']['sub'])
print(timetable['wednesday']['h3']['sub'])
print(timetable['thursday']['h4']['sub'])
print(timetable['friday']['h5']['sub'])


